// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Quentin Lachery",
            "email": "quentin.lkss@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exercice-realise/{id}": {
            "put": {
                "description": "Met à jour les données d’un exercice réalisé",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices Réalisés"
                ],
                "summary": "Modifier un exercice réalisé",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'exercice réalisé",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données à modifier",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceRealiseInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceRealise"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Supprime une entrée exercice réalisé par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices Réalisés"
                ],
                "summary": "Supprimer un exercice réalisé",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'exercice réalisé",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exercices": {
            "get": {
                "description": "Retourne tous les exercices disponibles",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices"
                ],
                "summary": "Liste des exercices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Exercice"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Ajoute un nouvel exercice dans la base",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices"
                ],
                "summary": "Créer un exercice",
                "parameters": [
                    {
                        "description": "Exercice à créer",
                        "name": "exercice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Exercice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exercices/{id}": {
            "get": {
                "description": "Retourne les informations d’un exercice par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices"
                ],
                "summary": "Détail d’un exercice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l’exercice",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Exercice"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Met à jour un exercice existant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices"
                ],
                "summary": "Modifier un exercice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l’exercice",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Champs à modifier",
                        "name": "exercice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Exercice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Supprime un exercice par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices"
                ],
                "summary": "Supprimer un exercice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l’exercice",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/poids": {
            "get": {
                "description": "Retourne toutes les entrées de poids enregistrées, triées par date décroissante",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poids"
                ],
                "summary": "Liste des poids",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Poids"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Enregistre une nouvelle valeur de poids pour une date donnée",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poids"
                ],
                "summary": "Créer une entrée de poids",
                "parameters": [
                    {
                        "description": "Poids à enregistrer",
                        "name": "poids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PoidsInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Poids"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/poids/{id}": {
            "put": {
                "description": "Met à jour la valeur du poids pour une entrée donnée",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poids"
                ],
                "summary": "Modifier un poids existant",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'entrée poids",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelle valeur du poids",
                        "name": "poids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PoidsUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Poids"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Supprime une entrée de poids par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poids"
                ],
                "summary": "Supprimer une entrée poids",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'entrée poids",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/seances": {
            "get": {
                "description": "Retourne toutes les séances enregistrées",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Séances"
                ],
                "summary": "Liste des séances",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Seance"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Ajoute une nouvelle séance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Séances"
                ],
                "summary": "Créer une séance",
                "parameters": [
                    {
                        "description": "Séance à enregistrer",
                        "name": "seance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SeanceInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Seance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/seances/{id}": {
            "get": {
                "description": "Retourne une séance par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Séances"
                ],
                "summary": "Détail d'une séance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la séance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Seance"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Met à jour une séance existante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Séances"
                ],
                "summary": "Modifier une séance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la séance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Champs à modifier",
                        "name": "seance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SeanceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Seance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Supprime une séance par ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Séances"
                ],
                "summary": "Supprimer une séance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la séance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/seances/{id}/exercices": {
            "get": {
                "description": "Retourne tous les exercices associés à une séance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices Réalisés"
                ],
                "summary": "Liste des exercices réalisés pour une séance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la séance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExerciceRealise"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Ajoute un exercice avec ses performances à une séance existante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercices Réalisés"
                ],
                "summary": "Ajouter un exercice réalisé à une séance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la séance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Détails de l'exercice",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceRealiseInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ExerciceRealise"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Exercice": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "groupe_musculaire": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nom": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ExerciceInput": {
            "type": "object",
            "properties": {
                "groupe_musculaire": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ExerciceRealise": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "exercice": {
                    "$ref": "#/definitions/models.Exercice"
                },
                "exercice_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ordre": {
                    "type": "integer"
                },
                "poids": {
                    "type": "number"
                },
                "reps": {
                    "type": "integer"
                },
                "rpe": {
                    "type": "number"
                },
                "seance_id": {
                    "type": "integer"
                },
                "series": {
                    "type": "integer"
                }
            }
        },
        "models.ExerciceRealiseInput": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "exercice_id": {
                    "type": "integer"
                },
                "ordre": {
                    "type": "integer"
                },
                "poids": {
                    "type": "number"
                },
                "reps": {
                    "type": "integer"
                },
                "rpe": {
                    "type": "number"
                },
                "series": {
                    "type": "integer"
                }
            }
        },
        "models.Poids": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "valeur": {
                    "description": "en kg",
                    "type": "number"
                }
            }
        },
        "models.PoidsInput": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "format YYYY-MM-DD",
                    "type": "string"
                },
                "valeur": {
                    "description": "en kg",
                    "type": "number"
                }
            }
        },
        "models.PoidsUpdate": {
            "type": "object",
            "properties": {
                "valeur": {
                    "type": "number"
                }
            }
        },
        "models.Seance": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "facultatif",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "description": "jour de la séance",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "description": "muscu, natation, cardio...",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.SeanceInput": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "date": {
                    "description": "\"YYYY-MM-DD\"",
                    "type": "string"
                },
                "type": {
                    "description": "muscu, piscine, etc.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8020",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API App-Sport",
	Description:      "API de suivi de poids et séances d'entraînement",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
