basePath: /
definitions:
  models.Exercice:
    properties:
      created_at:
        type: string
      groupe_musculaire:
        type: string
      id:
        type: integer
      nom:
        type: string
      type:
        type: string
      updated_at:
        type: string
    type: object
  models.ExerciceInput:
    properties:
      groupe_musculaire:
        type: string
      nom:
        type: string
      type:
        type: string
    type: object
  models.Poids:
    properties:
      createdAt:
        type: string
      date:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      valeur:
        description: en kg
        type: number
    type: object
  models.PoidsInput:
    properties:
      date:
        description: format YYYY-MM-DD
        type: string
      valeur:
        description: en kg
        type: number
    type: object
  models.PoidsUpdate:
    properties:
      valeur:
        type: number
    type: object
host: localhost:8020
info:
  contact:
    email: quentin.lkss@gmail.com
    name: Quentin Lachery
  description: API de suivi de poids et séances d'entraînement
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: API App-Sport
  version: "1.0"
paths:
  /exercices:
    get:
      description: Retourne tous les exercices disponibles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Exercice'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Liste des exercices
      tags:
      - Exercices
    post:
      consumes:
      - application/json
      description: Ajoute un nouvel exercice dans la base
      parameters:
      - description: Exercice à créer
        in: body
        name: exercice
        required: true
        schema:
          $ref: '#/definitions/models.ExerciceInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Exercice'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Créer un exercice
      tags:
      - Exercices
  /exercices/{id}:
    delete:
      description: Supprime un exercice par son ID
      parameters:
      - description: ID de l’exercice
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Supprimer un exercice
      tags:
      - Exercices
    get:
      description: Retourne les informations d’un exercice par son ID
      parameters:
      - description: ID de l’exercice
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exercice'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Détail d’un exercice
      tags:
      - Exercices
    put:
      consumes:
      - application/json
      description: Met à jour un exercice existant
      parameters:
      - description: ID de l’exercice
        in: path
        name: id
        required: true
        type: integer
      - description: Champs à modifier
        in: body
        name: exercice
        required: true
        schema:
          $ref: '#/definitions/models.ExerciceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exercice'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Modifier un exercice
      tags:
      - Exercices
  /poids:
    get:
      description: Retourne toutes les entrées de poids enregistrées, triées par date
        décroissante
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Poids'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Liste des poids
      tags:
      - Poids
    post:
      consumes:
      - application/json
      description: Enregistre une nouvelle valeur de poids pour une date donnée
      parameters:
      - description: Poids à enregistrer
        in: body
        name: poids
        required: true
        schema:
          $ref: '#/definitions/models.PoidsInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Poids'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Créer une entrée de poids
      tags:
      - Poids
  /poids/{id}:
    delete:
      description: Supprime une entrée de poids par son ID
      parameters:
      - description: ID de l'entrée poids
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Supprimer une entrée poids
      tags:
      - Poids
    put:
      consumes:
      - application/json
      description: Met à jour la valeur du poids pour une entrée donnée
      parameters:
      - description: ID de l'entrée poids
        in: path
        name: id
        required: true
        type: integer
      - description: Nouvelle valeur du poids
        in: body
        name: poids
        required: true
        schema:
          $ref: '#/definitions/models.PoidsUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Poids'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Modifier un poids existant
      tags:
      - Poids
swagger: "2.0"
