services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lukyss
      POSTGRES_PASSWORD: lukyss
      POSTGRES_DB: app_sport
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
